"""Auto-Fix PR agent — generates patches and creates GitHub PRs for verified findings."""
import json
import os
import re
from typing import Any, Dict, List

from tools.registry import register_tool


@register_tool(
    name="generate_fix_pr",
    description="Generate an auto-fix pull request for a verified security finding. "
    "Creates a branch, applies the fix, commits, and opens a PR on GitHub.",
    category="report",
    requires_provider=False,
)
async def generate_fix_pr(
    repo_path: str,
    finding: Dict[str, Any],
    github_token: str = "",
) -> Dict[str, Any]:
    """Generate auto-fix PR for a vulnerability finding.

    Args:
        repo_path: Local path to the git repository.
        finding: Dict with 'title', 'severity', 'file_path', 'line_number', 'fixed_code', 'description'.
        github_token: GitHub personal access token for PR creation.
    """
    import subprocess
    import uuid

    if not os.path.isdir(os.path.join(repo_path, ".git")):
        return {"status": "error", "message": f"Not a git repository: {repo_path}"}

    title = finding.get("title", "Security Fix")
    severity = finding.get("severity", "Medium")
    file_path = finding.get("file_path", "")
    fixed_code = finding.get("fixed_code", "")
    description = finding.get("description", "")

    # Sanitize branch name — only allow safe characters
    slug = re.sub(r'[^a-z0-9._-]', '-', title.lower())[:40]
    branch = f"fix/sec-llm-{slug}-{str(uuid.uuid4())[:6]}"

    try:
        # Create branch
        subprocess.run(["git", "-C", repo_path, "checkout", "-b", branch], capture_output=True, check=True)

        # Apply fix (resolve path relative to repo)
        if file_path and fixed_code:
            abs_path = os.path.join(repo_path, file_path)
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)
            with open(abs_path, "w", encoding="utf-8") as f:
                f.write(fixed_code)
            subprocess.run(["git", "-C", repo_path, "add", file_path], capture_output=True, check=True)

            # Commit
            commit_msg = f"fix(security): {title}\n\nSeverity: {severity}\n{description[:200]}"
            subprocess.run(["git", "-C", repo_path, "commit", "-m", commit_msg], capture_output=True, check=True)

            # Push
            subprocess.run(["git", "-C", repo_path, "push", "origin", branch], capture_output=True, check=True)
        else:
            return {"status": "error", "message": "Finding must include file_path and fixed_code"}

        # Create PR via GitHub CLI
        pr_body = f"""## Auto-Fix: {title}

**Severity**: {severity}
**File**: {file_path}
**Description**: {description}

> Generated by Sec-LLM Agent Platform"""
        result = subprocess.run(
            ["gh", "pr", "create", "--title", f"fix(security): {title}",
             "--body", pr_body, "--base", "main", "--head", branch],
            capture_output=True, text=True, cwd=repo_path,
            env={**os.environ, "GITHUB_TOKEN": github_token},
        )

        pr_url = result.stdout.strip() if result.returncode == 0 else ""
        return {
            "status": "success",
            "branch": branch,
            "pr_url": pr_url,
            "message": "Auto-fix PR created" if pr_url else f"PR creation failed: {result.stderr[:500]}",
        }
    except subprocess.CalledProcessError as e:
        return {"status": "error", "message": f"Git operation failed: {e.stderr[:500] if e.stderr else str(e)}"}
    except Exception as e:
        return {"status": "error", "message": str(e)[:500]}
